baseurl = "/"
languageCode = "en-us"
defaultContentLanguage = "en-us"
title = "Current Issues in SLA"
theme = "material"
#disqusShortname = ""
# googleAnalytics = ""
paginate = 7
relativeurls = true
publishDir = "./docs"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]


[permalinks]
  post = "/:year/:month/:slug/"

[taxonomies]
  tag = "tags"
  category = "categories"
  archive = "archives"

[author]
  name = "Joseph V. Casillas"
  bio = ""
  job = "Assstant Professor"
  location = "Rutgers University"
  gravatarEmail = "joseph.casillas@rutgers.edu"
  # Your profile picture
#  picture = ""
  twitter = "jvcasill"
 
# Menu Configuration
[[menu.main]]
  weight = 1
  identifier = "home"
  name = "Home"
  pre = "<i class=\"sidebar-button-icon fa fa-lg fa-home\"></i>"
  url = "/"
[[menu.main]]
  weight = 2
  identifier = "modules"
  name = "Modules"
  pre = "<i class=\"material-icons\">dashboard</i>"
  url = "/modules"  
[[menu.main]]
  weight = 3
  identifier = "tools"
  name = "Tools"
  pre = "<i class=\"material-icons\">build</i>"
  url = "/tools"
[[menu.main]]
  weight = 4
  identifier = "syllabus"
  name = "Syllabus"
  pre = "<i class=\"material-icons\">date_range</i>"
  url = "/syllabus"
[[menu.main]]
  weight = 5
  identifier = "policies"
  name = "Policies"
  pre = "<i class=\"material-icons\">gavel</i>"
  url = "/policies"

[[menu.footer]]
  weight = 1
  identifier = "Rutgers"
  name = "Rutgers Span-Port"
  pre = "<i class=\"button-icon fa fa-2x fa-map-marker\"></i>"
  url = "http://span-port.rutgers.edu"
[[menu.footer]]
  weight = 2
  identifier = "GitHub"
  name = "GitHub"
  pre = "<i class=\"button-icon fa fa-2x fa-github\"></i>"
  url = "https://github.com/jvcasillas/"



[params]
  dateFormat = "January 2, 2006"
  background = "https://i.imgur.com/77Ltere.jpg"
  favicon = "img/favicon.ico"

